services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-dock
    environment:
      POSTGRES_DB: aixsoftdev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker/volumes/postgres-dock
